services:
  db:
    image: postgres:latest
    container_name: postgres_notes
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_notes:/var/lib/postgresql/notes

volumes:
  postgres_notes: